-- Cloud SQL / local Postgres schema for the workplace vignette study.
-- Apply once to an empty database:
--   psql "$DATABASE_URL" -f db/schema.sql

create table if not exists public.participants (
  pid text primary key,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  assignment_slot integer unique,
  vignette_order text[],
  introduction_reading_time_ms integer,
  introduction_completed_at timestamptz,
  constraint participants_pid_format
    check (pid ~ '^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$'),
  constraint participants_assignment_slot_range
    check (assignment_slot is null or assignment_slot between 1 and 500),
  constraint participants_vignette_order_size
    check (vignette_order is null or cardinality(vignette_order) = 8),
  constraint participants_introduction_time_range
    check (
      introduction_reading_time_ms is null
      or introduction_reading_time_ms between 0 and 86400000
    )
);

create table if not exists public.vignette_responses (
  id bigint generated by default as identity primary key,
  pid text not null references public.participants(pid) on delete restrict,
  vignette_id text not null,
  vignette_number integer not null check (vignette_number between 1 and 32),
  task_type text not null,
  task_type_jitter_v text,
  directedness text not null,
  directedness_jitter_v text,
  data_access text not null,
  data_access_jitter_v text,
  visibility text not null,
  visibility_jitter_v text,
  full_vignette_text text not null,
  q1_value_feedback text not null,
  q2_seek_feedback text not null,
  q3_incorporate_feedback text not null,
  q4_comfortable_feedback text not null,
  q5_express_frustrations text not null,
  q6_rather_work_without text not null,
  time_spent_ms integer not null check (time_spent_ms >= 0),
  started_at timestamptz not null,
  submitted_at timestamptz not null default now(),
  unique (pid, vignette_number),
  unique (pid, vignette_id)
);

create or replace function public.register_participant(
  participant_pid text,
  counterbalance_orders jsonb
)
returns table (
  pid text,
  assignment_slot integer,
  vignette_order text[]
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  next_slot integer;
  selected_order text[];
  existing_unassigned boolean;
begin
  if participant_pid !~ '^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$' then
    raise check_violation using message = 'Invalid participant ID.';
  end if;

  if jsonb_typeof(counterbalance_orders) <> 'array'
     or jsonb_array_length(counterbalance_orders) < 1 then
    raise check_violation using message = 'Invalid counterbalance table.';
  end if;

  -- Serialize assignment so concurrent starts cannot receive the same slot.
  perform pg_advisory_xact_lock(20260715135000);

  select exists (
    select 1
    from public.participants p
    where p.pid = participant_pid and p.assignment_slot is null
  )
  into existing_unassigned;

  if exists (
    select 1
    from public.participants p
    where p.pid = participant_pid and p.assignment_slot is not null
  ) then
    raise unique_violation using message = 'Participant ID already exists.';
  end if;

  select coalesce(max(p.assignment_slot), 0) + 1
  into next_slot
  from public.participants p;

  if next_slot > jsonb_array_length(counterbalance_orders) then
    raise check_violation using message = 'All assignment slots are filled.';
  end if;

  select array_agg(item.value order by item.ordinality)
  into selected_order
  from jsonb_array_elements_text(
    counterbalance_orders -> (next_slot - 1)
  ) with ordinality as item(value, ordinality);

  if cardinality(selected_order) <> 8 then
    raise check_violation using message = 'Invalid assigned vignette order.';
  end if;

  if existing_unassigned then
    update public.participants p
    set assignment_slot = next_slot,
        vignette_order = selected_order
    where p.pid = participant_pid;
  else
    insert into public.participants (
      pid,
      assignment_slot,
      vignette_order
    )
    values (
      participant_pid,
      next_slot,
      selected_order
    );
  end if;

  return query
  select p.pid, p.assignment_slot, p.vignette_order
  from public.participants p
  where p.pid = participant_pid;
end;
$$;

create or replace view public.analysis_responses as
select
  r.pid as "Participant ID",
  p.assignment_slot as "Counterbalance Assignment Slot",
  p.introduction_reading_time_ms as "Introduction Reading Time (ms)",
  r.vignette_number as "Vignette Position",
  r.vignette_id as "Vignette ID",
  r.task_type as "Task Type",
  r.task_type_jitter_v as "Task Type Jitter Version",
  r.directedness as "Directedness",
  r.directedness_jitter_v as "Directedness Jitter Version",
  r.data_access as "Data Access",
  r.data_access_jitter_v as "Data Access Jitter Version",
  r.visibility as "Visibility",
  r.visibility_jitter_v as "Visibility Jitter Version",
  r.full_vignette_text as "Full Vignette Text",
  r.q1_value_feedback as "Q1 - Value Sam's Feedback",
  r.q2_seek_feedback as "Q2 - Seek Sam's Feedback",
  r.q3_incorporate_feedback as "Q3 - Incorporate Sam's Feedback",
  r.q4_comfortable_feedback as "Q4 - Comfortable with Sam's Feedback",
  r.q5_express_frustrations as "Q5 - Express Frustrations to Sam",
  r.q6_rather_work_without as "Q6 - Rather Work Without Sam",
  r.time_spent_ms as "Vignette Reading and Response Time (ms)",
  r.submitted_at as "Vignette Submitted At"
from public.vignette_responses r
join public.participants p on p.pid = r.pid
order by r.pid, r.vignette_number;
